# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main, development ]
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
# Set docker image names.
      - name: Setup env variables
        run: |
          echo "DOCKER_SERVICE=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

# Login against a Docker registry except on PR
# https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

# if below step is skipped this build is a tag build. Can be used for skipping other steps.
      - name: Is Tag Build
        id: tag
        if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Set Branch Name
        id: branch
        if: ${{ contains('main,development', github.ref_name) }}
        run: |
          branch_name=${GITHUB_REF##*/}
          if [[ "$branch_name" == "development" ]]; then
            echo "branch=test" >> $GITHUB_OUTPUT
          elif [[ "$branch_name" == "main" ]]; then
            echo "branch=prod" >> $GITHUB_OUTPUT
          else
            echo "branch=unknown" >> $GITHUB_OUTPUT
          fi

# Build
      - name: Build
        run: ./build/build.sh ${{ env.DOCKER_SERVICE }} ${{ github.event.repository.url }} ${{ steps.branch.outputs.branch }}

# Push to Github
      - name: Tag service git id docker image
        run: ./build/docker-tag.sh ${{ env.DOCKER_SERVICE }}:latest ${{ env.DOCKER_SERVICE }}:${{ github.sha }}

      - name: Tag service dev docker image
        run: ./build/docker-tag.sh ${{ env.DOCKER_SERVICE }}:latest ${{ env.DOCKER_SERVICE }}:dev

      - name: Push dev docker image.
        run: ./build/docker-push.sh ${{ env.DOCKER_SERVICE }}:dev

      - name: Push service git id docker image.
        run: ./build/docker-push.sh ${{ env.DOCKER_SERVICE }}:${{ github.sha }}

      - name: Push latest service docker image
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./build/docker-push.sh ${{ env.DOCKER_SERVICE }}:latest

      - name: Tag version service docker image
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./build/docker-tag.sh ${{ env.DOCKER_SERVICE }}:latest ${{ env.DOCKER_SERVICE }}:${{ steps.tag.outputs.VERSION }}

      - name: Push version service docker image.
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./build/docker-push.sh ${{ env.DOCKER_SERVICE }}:${{ steps.tag.outputs.VERSION }}

  # Update verion i config       
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        if: ${{ steps.branch.conclusion != 'skipped' && steps.branch.outputs.branch != 'unknown' }}
        with:
          repository: Randers-Kommune-Digitalisering/kithosting-randers-kommune-apps
          ref: ${{ steps.branch.outputs.branch }}
          path: infrastructure
          ssh-key: ${{ secrets.ACCESS_ARGO_APPS }}
          
      - name: Install yq
        if: ${{ steps.branch.conclusion != 'skipped' && steps.branch.outputs.branch != 'unknown' }}
        run: |
          sudo apt install -y jq

      - name: Update version
        if: ${{ steps.branch.conclusion != 'skipped' && steps.branch.outputs.branch != 'unknown' }}
        run: |
          yq e ".service.image.tag = \"${{ github.sha }}\"" -i infrastructure/budget-word-app/values.yaml

      - name: Commit and push
        if: ${{ steps.branch.conclusion != 'skipped' && steps.branch.outputs.branch != 'unknown' }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          cd infrastructure
          if [[ -n "$(git status -s)" ]]; then
            git commit -am "Update version"
            git push
          fi
